apiVersion: apps/v1
kind: Deployment
metadata:
  name: delete-task
spec:
  replicas: 3
  selector:
    matchLabels:
      app: delete-task
  template:
    metadata:
      labels:
        app: delete-task
    spec:
      containers:
      - name: delete-task
        env:
          - name: CONNECTION_STRING
            value: Driver={ODBC Driver 18 for SQL Server};Server=tcp:microtodoapp2007.database.windows.net,1433;Database=todo-db1;Uid=sql_admin;Pwd=Redhat@1234;Encrypt=yes;TrustServerCertificate=no;Connection Timeout=30;
        image: iamarund.azurecr.io/todo-delete-tasks-api:v1
        ports:
        - containerPort: 8000
